[package]
name = "conways_game_of_life"
version = "0.1.0"
edition = "2021"
authors = ["Z0tt3l", "ArcticSpaceFox"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
clap = "2.33.3"
ggez = "0.7.0"
rand = "0.8.3"
rayon = "1.5.0"